import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react';
import styles from '../styles/Home.module.css'

export default function Home() {

  const [testA, setTestA] = useState(Object);

  async function fetchSSEAPI() {
    const eventSource = new EventSource(`http://localhost:4011/sse/api/v1/stream`)
    eventSource.onmessage = function (event) {
      let event_data = JSON.parse(event.data)
      setTestA(event_data)
      if (event_data.status === 'FINISHED') {
        console.log('멈춰~~')
        eventSource.close()
      }
    }
  }

  useEffect(() => {
    fetchSSEAPI()
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {testA.status && testA.status}
    </div>
  )
}
